name: Tag CI

on:
  release:
    types:
      - published
      - edited

jobs:
  latest:
    name: Latest
    runs-on: ubuntu-latest
    steps:
      - name: Update latest tag
        uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish_latest_tag: true