name: Tag CI
on:
  release:
    types: [published, edited]
jobs:
  latest:
    name: Latest
    runs-on: windows-latest
    steps:
      - name: Update latest tag
        uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: "${{ secrets.GH_PAT }}"
        with:
          publish_latest_tag: true